
/*
Write a program to print the sum of all the numbers in the given array.
L = {23, 45, 32, 25, 46,33, 71, 90}
*/


// const input = require("readline-sync");
// let n = input.questionInt("enetr the length of the array:");
// let arr = [];
// let s = 0;
// let i = 0;


// for(let i = 0; i<n; i++)
// {
//   arr[i] = input.questionInt("enetr the element")
// }
// while (i<n) {

//   s = s+arr[i];
//  i++ 
// }
// console.log(s);






/*
Write a program to take 5 names from the user and print them.
 */





// const input = require("readline-sync");
// let n = input.questionInt("Enter the length of the array: ");
// let arr = [];

// for(let i = 0; i < n; i++) 
// { 
//   arr[i] = input.question("Enter the element: ");

// }

// for (let j = 0; j < n; j++)
//  {

//   console.log(arr[j]);
// }